config/routes.rb
Rails.application.routes.draw do


  get 'how_to_play', to: 'pages#how_to_play'
  
    namespace :admin do
      # admin/home
      get 'home/index', to: 'home#index'
  
      # admin/users
      resources :users, only: [:index, :show, :edit, :update, :destroy]
  
      # admin/quizs
      resources :quizs, only: [:index, :show, :edit, :update, :destroy]
  
      # admin/quiz_rooms
      resources :quiz_rooms, only: [:index, :show, :edit, :update, :destroy]
  
      # admin/genre
      resources :genre
    end


  namespace :public do
    # RoomAssociation関連
    resources :room_association, only: [:create, :destroy]
  
    # QuizRooms関連
    resources :quiz_rooms, only: [:destroy] do
      collection do
        get 'top'
        get 'join'
        get 'make'
        post 'create'
        get 'room'
        get 'quiz_select'
        get 'quiz_set'
        get 'develop_select'
        get 'develop_set'
      end

      member do
        post 'start_game' # ✅ IDを必須にする
        post 'waiting_game'
        post 'interval_game'
        patch :update_selected_choice
      end

    end
  
    # Quizs関連
    resources :quizs, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  
    # Follows関連
    resources :follows, only: [:create, :destroy]
  
    # Users関連
    resources :users, only: [:index, :show, :edit, :update] do
      post 'withdraw', on: :member
      collection do
        get 'search'  # 検索用ルート
      end
    end
  end




  root "home#index" # トップページ用
# 顧客用
# URL /customers/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'

}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @user = current_user if user_signed_in? # ログインユーザーを取得
      @quizzes = Quiz.includes(:genre, :creator).order(created_at: :desc).limit(5)
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/home/index.html.erb
<main class="bg-light text-center py-5">
  <div class="container">
    <!-- ゲームタイトル -->
    <h1 class="display-4 text-primary font-weight-bold">Which_one_game</h1>
    <p class="lead text-dark">～今のはどっち？～</p>
    
    <!-- ボタンセクション -->
    <div class="mt-4">
      <% if user_signed_in? %>
        <%= link_to "ゲーム開始", top_public_quiz_rooms_path, class: "btn btn-warning btn-lg mx-2" %>
        <%= link_to "マイページ", public_user_path(current_user), class: "btn btn-success btn-lg mx-2" %>
        <%= link_to "クイズ一覧へ", public_quizs_path, class: "btn btn-secondary btn-lg mx-2" %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary btn-lg mx-2" %>
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-danger btn-lg mx-2" %>
      <% end %>
    </div>

    <!-- ゲームの遊び方 -->
    <section class="mt-5">
      <h2 class="text-danger font-weight-bold">ゲームの遊び方</h2>
      <p class="text-muted">
        出題者が読み上げたのは選択肢のどっちなのか考えよう！</br>
      </p>
    </section>


    <section class="mt-5">
    <h2 class="text-primary font-weight-bold">クイズの例</h2>
  
    <table class="table table-striped table-bordered">
      <thead class=" table-danger">
        <tr>
          <th class="text-left" style="width: 50%;">問題文</th>
          <th class="text-left">選択肢1</th>
          <th class="text-left">選択肢2</th>
        </tr>
      </thead>
      <tbody>
        <% @quizzes.each do |quiz| %>
          <tr>
            <td class="text-left fw-bold table-primary"><%= quiz.question_text %></td>
            <td class="text-left"><%= quiz.choice_1 %></td>
            <td class="text-left"><%= quiz.choice_2 %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
  
  </div>
</main>